#Numpy is a python library with support for large arrays and matrices, it also let's us operate on them by using several mathematical functions.

In [2]:
some_list = [1, 2, 3]

In [3]:
import numpy as np #importing numpy as np

In [4]:
np.array(some_list) #to convert a list to nparray

array([1, 2, 3])

In [6]:
np.arange(0, 10+1, 2) #get a nparray from arguments(start, stop, interval)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros((2,2)) #get a nparray of zeros

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,3)) #get a nparray of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0, 5, 10) #get a nparray of evenly spaced nums with arguments(min, max, interval)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(4) #get an nparray of ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5) #get an nparray from uniform distribution with size as argument

array([0.38747336, 0.60007783, 0.25624653, 0.27218347, 0.25945587])

In [14]:
np.random.rand(5,5) #a 2d nparray from uniform distribution

array([[0.85324387, 0.11120182, 0.14306011, 0.76788459, 0.44445348],
       [0.1580656 , 0.58922064, 0.39499317, 0.87696023, 0.16435173],
       [0.35727164, 0.45254839, 0.38870808, 0.76233898, 0.1665017 ],
       [0.18585237, 0.6667147 , 0.48389822, 0.12294509, 0.40619864],
       [0.52286948, 0.16888266, 0.0884555 , 0.59911299, 0.83324936]])

In [15]:
np.random.randn(5) #get an nparray from from standard normal distribution

array([ 0.93572009, -0.74169139,  1.2900841 , -0.38846899,  0.92645048])

In [16]:
np.random.randn(5,5) #a 2d nparray from normal distribution

array([[ 1.52332354,  0.89089559,  0.43496458, -1.19344963,  1.48487466],
       [ 0.4403737 , -1.28895326, -1.29233576,  0.45438753, -0.50759944],
       [ 0.48744112,  0.63313946, -0.67644535, -0.84476243, -1.06577375],
       [ 0.2563145 ,  0.24812185, -1.716193  , -0.59646296,  0.07126344],
       [ 0.49605729,  0.22590368,  0.43736037, -1.26218477,  0.35336629]])

In [18]:
np.random.randint(1, 10, 10) #produces a random int from arguments(min, max, numberOfInts)

array([6, 4, 4, 3, 2, 5, 9, 6, 5, 9])

In [21]:
arr = np.arange(25)
arr #get an nparray in a range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0, 50, 10)
ranarr #get an nparray of random nums from arguments(min, max, size)

array([13, 21, 33, 47, 17, 30, 36,  8,  0, 48])

In [23]:
arr.reshape(5,5) #reshape an nparray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max() #get the max value from nparray

48

In [26]:
ranarr.min() #get the min value from nparray

0

In [28]:
ranarr.argmax() #get the location of the max value from nparray

9

In [29]:
ranarr.argmin() #get the location of the min value from nparray

8

In [30]:
arr.shape #get the shape of the nparray

(25,)

In [31]:
arr = arr.reshape(5,5)
arr.shape #resize and get the shape of the nparray

(5, 5)

In [32]:
arr.dtype #get the data-type of the nparray

dtype('int32')

In [33]:
from numpy.random import randint
randint(2, 10) #if you get bored typing the long package

4

#Indexing and selecting elements from an nparray

In [34]:
arr = np.arange(0, 10+1)
arr #another nparray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[1:5] #everything from x to y

array([1, 2, 3, 4])

In [37]:
arr[:6] #everything upto 6

array([0, 1, 2, 3, 4, 5])

In [38]:
arr[4:] #everything from 4 

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[0:5] = 100 #broadcasting the value
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [41]:
arr = np.arange(0, 10+1)
arr #resetting array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
aSliceOfarr = arr[0:6] #making a slice of the array
aSliceOfarr

array([0, 1, 2, 3, 4, 5])

In [44]:
aSliceOfarr[:] = 9 #carful with broadcasting
aSliceOfarr

array([9, 9, 9, 9, 9, 9])

In [45]:
arr #its not a copy but a view

array([ 9,  9,  9,  9,  9,  9,  6,  7,  8,  9, 10])

In [46]:
arrCopy = arr.copy() #use copy() method to create a copy

In [52]:
arr = np.arange(0, 10+1)
arr #resetting array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arrCopy[:] = 9 #after using copy it wont modify the original arr
arrCopy

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [54]:
arr #its still the same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr2d #a 2d nparray

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr2d[2][1] #indexing a 2d array

40

In [61]:
arr2d[2, 1] #indexing a 2d array in another way

40

In [62]:
arr2d[:2, 1:] #get everything upto row2 but everything from col1

array([[10, 15],
       [25, 30]])

In [63]:
arr = np.arange(1, 10+1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
boolArr = arr > 5 #boolean nparray
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [66]:
arr[boolArr] #using boolArr to connditionally select values

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr<3] #another condition

array([1, 2])

In [71]:
arr2d = np.arange(50).reshape(5, 10) #sample arr
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
arr2d[1:3, 3:5] #slicing an array in a weird way

array([[13, 14],
       [23, 24]])

#Numpy operations

In [74]:
arr = np.arange(0, 10+1)
arr #making an array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr + arr #adding

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
arr - arr #subtracting

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
arr * arr #multiplying

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
arr + 100 #adding with constant

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [79]:
arr * 100 #multiplying with constant

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [80]:
arr / arr #dividing with constant

C:\Users\yeshw\AppData\Local\Temp/ipykernel_14408/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [81]:
arr ** 2 #taking power of with a constant

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [82]:
np.sqrt(arr) #taking square root of al elements 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [83]:
np.exp(arr) #taking exponential of all elements 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [84]:
np.max(arr) #getting the max value

10

In [85]:
np.sin(arr) #taking the sin value of all elements 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [86]:
np.log(arr) #taking the log of all values

C:\Users\yeshw\AppData\Local\Temp/ipykernel_14408/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#checkout docs.scipy.org/doc/numpy/reference/ufuncs.html

#Summary

#creating an array of 10 zeros

In [87]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#creating an array of 10 ones

In [88]:
np.ones(1)

array([1.])

#create an array of 10 fives

In [89]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#create an array from 10 to 50

In [90]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#creating an array of even ints from 10 to 51

In [91]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#creating a 3x3 matrix from int 0 to 8

In [99]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#creating a 3x3 identity matrix

In [100]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#using numpy to generate a random number between 0 to 1

In [104]:
np.random.rand(1)

array([0.03766378])

#generate 25 random numbers evenly spaced from a standard normal distribution

In [105]:
np.random.randn(25)

array([-0.98382562, -0.11410459, -1.45255798, -0.06773944, -0.63925269,
       -0.15932651,  0.72851969, -0.3192783 , -1.01418405,  0.26145445,
       -0.2762289 ,  1.20876811, -0.97339608, -0.4141052 ,  0.93296715,
       -0.93661855,  0.25257189, -1.03030115, -0.66285076, -0.33531362,
       -0.6466048 ,  0.29390005, -0.85890963, -1.21135737, -1.05191364])

#creating this weird matrix

In [108]:
np.arange(1,100+1).reshape(10, 10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#creating 20 linearly spaced points between 0 & 1

In [109]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])